version: "3.9"

services:
  node-red:
    build: ./node-red
    restart: always
    user: root
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 1880:1880
    volumes:
      - /config/node-red/flows.json:/data/flows.json
      - /config/node-red/settings.js:/data/settings.js
      - /data/node-red:/context
    devices:
      - /dev/ttyACM0
#      - /dev/video0
  ssh:
    build: ./ssh
    restart: always
    command: |
      -R 127.1.0.1:34968:node-red:1880
      -o "ProxyCommand nc -X 5 -x tor:9050 %h %p"
      rpi@biondemos.com
      -p 54545
    volumes:
      - /config/autossh/id_ed25519:/id_ed25519:ro
  tor:
    build: ./tor
    restart: always